server:
  port: ${port:8080}
spring:
  application:
    name: edgeserver

security:
  basic:
    enabled: false


zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: authserver
    registration:
      path: /register/**
      serviceId: registration
    ui:
      path: /**
      serviceId: UI
    grafana:
      path: /internal/grafana/**
      url: http://pi41:9822
    influx:
      path: /internal/influx/**
      url: http://pi41:8086
  ignoredPatterns: /**/admin/**
  ignoredServices: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://management-server:8080/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      preferIpAddress: true