eurekaserver:
   image: dilgerm/rpi-eurekaserver:78
   ports:
   - "8761:8761"
   container_name: "eurekaserver"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi31:12201
metrics-server:
   image: dilgerm/rpi-metrics-server:78
   ports:
   - "9821:8080"
   container_name: "metrics-server"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi31:12201
authserver:
   image: dilgerm/rpi-auth-server:75
   container_name: authserver
   ports:
   - "9820:8080"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi31:12201
bootadmin:
   image: dilgerm/rpi-bootadmin:75
   ports:
   - "9800:8080"
   container_name: "bootadmin"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi31:12201
ui:
   image: dilgerm/rpi-billy-ui:77
   container_name: "ui"
   ports:
   - "8080:8080"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
invoices:
   image: dilgerm/rpi-billy-invoices:78
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
expenses:
   image: dilgerm/rpi-billy-expenses:74
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
customers:
   image: dilgerm/rpi-billy-customers:77
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
reporting:
   image: dilgerm/rpi-billy-reporting:77
   expose:
   - "8081"
   ports:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
#templates:
#   image: dilgerm/rpi-billy-templates:75
#   expose:
#   - "8081"
#   log_driver: "gelf"
#   log_opt:
#    gelf-address: udp://pi31:12201
repository:
   image: dilgerm/rpi-billy-repository:78
   expose:
   - "8080"
   environment:
   - user_email=martin@effectivetrainings.de
   - user_apiKey=b7cd951bc464a9ab45640730001d64edBRI3mrXeTVGh2dT43ff6Z4FCXSBDSnMk
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi31:12201
#elasticsearch:
#  image: itwars/rpi-elasticsearch
#  container_name: elasticsearch
#  environment:
#  - constraint:node==pi24
#  ports:
#  - "9200:9200"
#  - "9300:9300"
#logstash:
#  image: dilgerm/rpi-logstash:49
#  container_name: logstash
#  expose:
#  - "5000"
#  ports:
#  - "12201:12201/udp"
#needs to run on pi31 to be able to use gelf-logging
#  environment:
#  - constraint:node==pi31
#kibana:
#  image: dilgerm/rpi-billy-kibana:49
#  ports:
#  - "9681:80"
influxdb:
  image: dilgerm/rpi-influxdb
  container_name: "influxdb"
  ports:
  - "8086"
  - "8083"
  - "25826:25826"
  log_driver: "gelf"
  log_opt:
   gelf-address: udp://pi31:12201
redis:
  container_name: redis
  image: hypriot/rpi-redis
  ports:
  - "6379"
mongo:
  container_name: mongo
  image: sponki/rpi-mongo
  volumes:
   - /data/db
  expose:
  - "27017"
  ports:
  - "27017"
rabbitmq:
  hostname: rabbitmq
  image: dilgerm/rpi-rabbitmq
  ports:
  - "5672"
  - "15672:15672"
