management-server:
   image: dilgerm/rpi-management-server:111
   ports:
   - "8761:8080"
   container_name: "management-server"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi26:12201
authserver:
   image: dilgerm/rpi-authserver:111
   container_name: authserver
   ports:
   - "9200:8080"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi26:12201
   environment:
    - constraint:node==pi28
ui:
   image: dilgerm/rpi-billy-ui:112
   container_name: "ui"
   ports:
   - "8080:8080"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
invoices:
   image: dilgerm/rpi-billy-invoices:111
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
expenses:
   image: dilgerm/rpi-billy-expenses:111
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
customers:
   image: dilgerm/rpi-billy-customers:111
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
registration:
   image: dilgerm/rpi-billy-registration:111
   expose:
   - "8081"
   ports:
   - "9823:8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
edge-server:
   image: dilgerm/rpi-edge-server:111
   expose:
   - "8081"
   ports:
   - "9823:8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
reporting:
   image: dilgerm/rpi-billy-reporting:111
   expose:
   - "8081"
   ports:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
repository:
   image: dilgerm/rpi-billy-repository:111
   expose:
   - "8080"
   environment:
   - user_email=martin@effectivetrainings.de
   - user_apiKey=b7cd951bc464a9ab45640730001d64edBRI3mrXeTVGh2dT43ff6Z4FCXSBDSnMk
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi26:12201
   extra_hosts:
   - "authserver:192.168.178.28"
