loadbalancer:
   build: loadbalancer
   ports:
   - "80:80"
eurekaserver:
   build: fb-eureka-server
   container_name: eurekaserver
   ports:
   - "8761:8761"
   expose:
   - "8761"
bootadmin:
   build: fb-boot-admin-server
   container_name: bootadmin
   ports:
   - "9800:8080"
metricsserver:
   build: fb-metrics-server
   container_name: metricsserver
   ports:
   - "9810:8080"
authserver:
   build: fb-auth-server
   container_name: authserver
   ports:
   - "9820:8080"
ui:
   build: fb-web
   expose:
   - "8080"
   ports:
   - "8080:8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
#reportingui:
#  build: fb-web-reporting
#  expose:
#  - "8081"
#  ports:
#  - "8081:8081"
#  command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
invoices:
   build: fb-invoices
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
expenses:
   build: fb-expenses
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
customers:
   build: fb-customers
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
reporting:
   build: fb-reporting
   expose:
   - "8081"
   ports:
   - "9999:8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
templates:
   build: fb-template
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
repository:
   build: fb-repository
   expose:
   - "8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   environment:
   - user_email
   - user_apiKey
   - spring.profiles.active=mock
elasticvolume:
   build: elasticsearch-volume
   mem_limit: 4m
elasticsearch:
  user: root
  build: elasticsearch
  container_name: elasticsearch
  expose:
  - "9200"
  - "9300"
  ports:
  - "9200:9200"
  - "9300:9300"
  volumes_from: ['elasticvolume']
logstash:
  build: logstash
  expose:
  - "5000"
kibana:
  build: kibana
  expose:
  - "80"
  ports:
  - "8090:80"
influxdb:
  image: tutum/influxdb
  container_name: influxdb
  ports:
  - "8083:8083"
  - "8086:8086"
  environment:
  - ADMIN_USER="root"
grafana:
  image: grafana/grafana
  ports:
  - "3000:3000"
  environment:
  - "GF_SECURITY_ADMIN_PASSWORD=secret"
mongo:
  container_name: mongo
  image: mongo
  volumes:
  - /data/db
  expose:
  - "27017"
  ports:
  - "27017:27017"
#mongographite:
#  build: mongo-graphite
#  links:
#  - graphite
#  - mongo
rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:3.5.1-management
  ports:
  - "5672:5672"
  #user guest / guest
  - "15672:15672"
redis:
  container_name: redis
  image: redis
  ports:
  - "6379"
