ui:
   build: fb-web
   hostname: fb-web
   ports:
   - "80:8080"
   links:
   - invoices
   - expenses
   - customers
   - templates
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   mem_limit: 324m
invoices:
   build: fb-invoices
   hostname: fb-invoices
   expose:
   - "8081"
   links:
   - repository:repository
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   mem_limit: 324m
expenses:
   build: fb-expenses
   hostname: fb-expenses
   expose:
   - "8081"
   links:
   - repository:repository
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   mem_limit: 324m
customers:
   build: fb-customers
   hostname: fb-customers
   expose:
   - "8081"
   links:
   - repository:repository
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   mem_limit: 324m
templates:
   build: fb-template
   hostname: fb-template
   expose:
   - "8081"
   links:
   - mongo
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   mem_limit: 324m
repository:
   build: fb-repository
   hostname: fb-repository
   expose:
   - "8080"
   links:
   - graphite
   command: java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=mock -jar /sources/app.jar
   environment:
   - user_email
   - user_apiKey
   mem_limit: 324m
mongo:
  image: dockerfile/mongodb
  volumes:
  - /data/db
  expose:
  - "27017"
  mem_limit: 512m

#graphite is currently only here as there is a problem in opening the socker (NullPointerException) if the container is not up.
graphite:
  image: hopsoft/graphite-statsd
  ports:
  - "8080"
  - "2003"
  - "2004"
  expose:
  - "2003"
  - "2004"
  - "8080"