eurekaserver:
   image: dilgerm/rpi-eurekaserver:101
   ports:
   - "8761:8761"
   container_name: "eurekaserver"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi28:12201
metrics-server:
   image: dilgerm/rpi-metrics-server:101
   ports:
   - "9821:8080"
   container_name: "metrics-server"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi28:12201
authserver:
   image: dilgerm/rpi-authserver:101
   container_name: authserver
   ports:
   - "9820:8080"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi28:12201
   environment:
    - constraint:node==pi23
bootadmin:
   image: dilgerm/rpi-bootadmin:101
   ports:
   - "9800:8080"
   container_name: "bootadmin"
   log_driver: "gelf"
   log_opt:
     gelf-address: udp://pi28:12201
ui:
   image: dilgerm/rpi-billy-ui:101
   container_name: "ui"
   ports:
   - "8080:8080"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
invoices:
   image: dilgerm/rpi-billy-invoices:101
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
expenses:
   image: dilgerm/rpi-billy-expenses:101
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
customers:
   image: dilgerm/rpi-billy-customers:101
   expose:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
registration:
   image: dilgerm/rpi-billy-registration:101
   expose:
   - "8081"
   ports:
   - "9823:8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
reporting:
   image: dilgerm/rpi-billy-reporting:101
   expose:
   - "8081"
   ports:
   - "8081"
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
repository:
   image: dilgerm/rpi-billy-repository:101
   expose:
   - "8080"
   environment:
   - user_email=martin@effectivetrainings.de
   - user_apiKey=b7cd951bc464a9ab45640730001d64edBRI3mrXeTVGh2dT43ff6Z4FCXSBDSnMk
   log_driver: "gelf"
   log_opt:
    gelf-address: udp://pi28:12201
   extra_hosts:
   - "authserver:192.168.178.28"
