loadbalancer:
   build: loadbalancer
   ports:
   - "80:80"
eurekaserver:
   build: fb-eureka-server
   hostname: eurekaserver
   ports:
   - "8761:8761"
   expose:
   - "8761"
ui:
   build: fb-web
   expose:
   - "8080"
   ports:
   - "8080:8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
reportingui:
  build: fb-web-reporting
  expose:
  - "8081"
  ports:
  - "8081:8081"
  command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
invoices:
   build: fb-invoices
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
expenses:
   build: fb-expenses
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
customers:
   build: fb-customers
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
reporting:
   build: fb-reporting
   expose:
   - "8081"
   ports:
   - "9999:8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
templates:
   build: fb-template
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
repository:
   build: fb-repository
   expose:
   - "8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   environment:
   - user_email
   - user_apiKey
#   - spring.profiles.active=mock
mongo:
  hostname: mongo
  image: mongo
  volumes:
  - /data/db
  expose:
  - "27017"
  ports:
  - "27017:27017"
rabbitmq:
  hostname: rabbitmq
  image: rabbitmq:3.5.1-management
  ports:
  - "5672:5672"
  - "15672:15672"