management-server:
   build: services/fb-management-server
   container_name: management-server
   dockerfile: Dockerfile-rpi
   ports:
   - "8761:8080"
   expose:
   - "8761"
authserver:
   build: services/fb-auth-server
   dockerfile: Dockerfile-rpi
   container_name: authserver
   ports:
   - "9820:8080"
ui:
   build: services/fb-web
   dockerfile: Dockerfile-rpi
   expose:
   - "8080"
   ports:
   - "8080:8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
registration:
   build: services/fb-registration
   dockerfile: Dockerfile-rpi
   expose:
   - "8081"
   ports:
   - "9823:8081"
#reportingui:
#  build: fb-web-reporting
#   dockerfile: Dockerfile-rpi
#  expose:
#  - "8081"
#  ports:
#  - "8081:8081"
#  command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
invoices:
   build: services/fb-invoices
   dockerfile: Dockerfile-rpi
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
expenses:
   build: services/fb-expenses
   dockerfile: Dockerfile-rpi
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
customers:
   build: services/fb-customers
   dockerfile: Dockerfile-rpi
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
reporting:
   build: services/fb-reporting
   dockerfile: Dockerfile-rpi
   expose:
   - "8081"
   ports:
   - "9999:8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
templates:
   build: services/fb-template
   expose:
   - "8081"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
repository:
   build: services/fb-repository
   dockerfile: Dockerfile-rpi
   expose:
   - "8080"
   command: java -Djava.security.egd=file:/dev/./urandom -jar /sources/app.jar
   environment:
   - user_email
   - user_apiKey
   - spring.profiles.active=mock
elasticvolume:
   build: infrastructure/elasticsearch-volume
   dockerfile: Dockerfile-rpi
   mem_limit: 4m
elasticsearch:
  user: root
  build: infrastructure/elasticsearch
  dockerfile: Dockerfile-rpi
  container_name: elasticsearch
  expose:
  - "9200"
  - "9300"
  ports:
  - "9200:9200"
  - "9300:9300"
  volumes_from: ['elasticvolume']
logstash:
  build: infrastructure/logstash
  dockerfile: Dockerfile-rpi
  expose:
  - "5000"
kibana:
  build: infrastructure/kibana
  dockerfile: Dockerfile-rpi
  expose:
  - "80"
  ports:
  - "8090:80"
influxdb:
  image: tutum/influxdb
  container_name: influxdb
  ports:
  - "8083:8083"
  - "8086:8086"
  environment:
  - ADMIN_USER="root"
grafana:
  image: grafana/grafana
  ports:
  - "3000:3000"
  environment:
  - "GF_SECURITY_ADMIN_PASSWORD=secret"
mongo:
  container_name: mongo
  image: mongo
  volumes:
  - /data/db
  expose:
  - "27017"
  ports:
  - "27017:27017"
#mongographite:
#  build: mongo-graphite
#  links:
#  - graphite
#  - mongo
rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:3.5.1-management
  ports:
  - "5672:5672"
  #user guest / guest
  - "15672:15672"
redis:
  container_name: redis
  image: redis
  ports:
  - "6379"
