server:
  port: 8090



security:
  basic:
    enabled: false

  oauth2:
    client:
            client-id: client
            client-secret: secret
            access-token-uri: http://authserver:8080/auth/oauth/token
            user-authorization-uri: http://authserver:8080/auth/oauth/authorize
            client-authentication-scheme: header
            use-current-uri:  true
