server:
  port: 8090



security:
  basic:
    enabled: false

  oauth2:
    client:
            client-id: client
            client-secret: secret
            access-token-uri: http://192.168.178.28:9200/auth/oauth/token
            user-authorization-uri: http://192.168.178.28:9200/auth/oauth/authorize
            client-authentication-scheme: header
            use-current-uri:  true
            scope: services