bind-address = "0.0.0.0"
port = 8086
reporting-disabled = false

[meta]
  dir = "/var/opt/influxdb/meta"

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083
  assets = "/opt/influxdb/current/admin"

[api]
  bind-address = "0.0.0.0"
  port = 8086

[opentsdb]
  enabled = false

[udp]
  enabled = false

[broker]
  dir = "/data/broker"
  enabled = true
  election-timeout = "0"

[data]
  dir = "/data/db"
  enabled = true
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"

[snapshot]
  enabled = false

[logging]
  write-tracing = false
  raft-tracing = false
  level  = "info"
  file   = "/opt/influxdb/shared/log.txt"

[monitoring]
  enabled = false

[debugging]
  pprof-enabled = false

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"
  disabled = false

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"

[collectd]
  enabled = true
  bind-address = ":25826" # the bind address
  database = "collectd" # Name of the database that will be written to
  batch-size = 5000 # will flush if this many points get buffered
  batch-pending = 10 # number of batches that may be pending in memory
  batch-timeout = "10s"
  read-buffer = 0 # UDP read buffer size, 0 means to use OS default
  typesdb = "/config/collectd_types.db"
